-- Your SQL goes here
CREATE TABLE IF NOT EXISTS uesr_details(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    uid INTEGER UNSIGNED  NOT NULL UNIQUE,

    signature TEXT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4