-- Your SQL goes here
CREATE TABLE IF NOT EXISTS users (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,

    name VARCHAR(32) NOT NULL,

    email VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(64)NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4