-- Your SQL goes here
CREATE TABLE IF NOT EXISTS users (
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,

    name VARCHAR(32) NOT NULL,

    email VARCHAR(128) NOT NULL,
    password VARCHAR(64)NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4