-- Your SQL goes here
CREATE TABLE IF NOT EXISTS todo_infos(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    uid INTEGER UNSIGNED  NOT NULL UNIQUE,

    title VARCHAR(128) NOT NULL,
    descript TEXT NOT NULL,
    ddl DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TODO TAG
CREATE TABLE IF NOT EXISTS todo_tags(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
    uid INTEGER UNSIGNED  NOT NULL UNIQUE,

    name VARCHAR(16) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tag todo connect
CREATE TABLE IF NOT EXISTS todo_tag_links(
    id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,

    tid INTEGER UNSIGNED  NOT NULL,
    gid INTEGER UNSIGNED  NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;